export const brazilStates = [
  { symbol: 'AC', label: 'Acre' },
  { symbol: 'AL', label: 'Alagoas' },
  { symbol: 'AP', label: 'Amapá' },
  { symbol: 'AM', label: 'Amazonas' },
  { symbol: 'BA', label: 'Bahia' },
  { symbol: 'CE', label: 'Ceará' },
  { symbol: 'DF', label: 'Distrito Federal' },
  { symbol: 'ES', label: 'Espírito Santo' },
  { symbol: 'GO', label: 'Goiás' },
  { symbol: 'MA', label: 'Maranhão' },
  { symbol: 'MT', label: 'Mato Grosso' },
  { symbol: 'MS', label: 'Mato Grosso do Sul' },
  { symbol: 'MG', label: 'Minas Gerais' },
  { symbol: 'PA', label: 'Pará' },
  { symbol: 'PB', label: 'Paraíba' },
  { symbol: 'PR', label: 'Paraná' },
  { symbol: 'PE', label: 'Pernambuco' },
  { symbol: 'PI', label: 'Piauí' },
  { symbol: 'RJ', label: 'Rio de Janeiro' },
  { symbol: 'RN', label: 'Rio Grande do Norte' },
  { symbol: 'RS', label: 'Rio Grande do Sul' },
  { symbol: 'RO', label: 'Rondônia' },
  { symbol: 'RR', label: 'Roraima' },
  { symbol: 'SC', label: 'Santa Catarina' },
  { symbol: 'SP', label: 'São Paulo' },
  { symbol: 'SE', label: 'Sergipe' },
  { symbol: 'TO', label: 'Tocantins' },
]
